---
ID: "0d736e5d-9e65-530f-9a8b-ed1100743a7a"
Parent: "befbde20-d9cd-5d07-b7bc-a491a1ef7e97"
Template: "befbde20-d9cd-5d07-b7bc-a491a1ef7e97"
Path: "/sitecore/templates/Project/Styleguide/Styleguide-ComponentParams/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230228T211941Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4fc4f776-693c-4dfb-8a3f-e50b0a4891ac"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230228T211941Z
