---
ID: "dc8dcc0f-a4de-5362-8c85-af30d7c45aed"
Parent: "e90418af-d3c3-5c40-8f26-a9e99b3fa430"
Template: "e90418af-d3c3-5c40-8f26-a9e99b3fa430"
Path: "/sitecore/templates/Project/Styleguide/Styleguide-Explanatory-Component/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230228T211937Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a39421df-63bb-47fc-a64b-54a68a5da552"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230228T211937Z
